{% set name = "napari-clusters-plotter" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-clusters-plotter-{{ version }}.tar.gz
  sha256: a883931bac88b78c5369268290b4c94f2b0a869ac518b074f2635c558f76dec6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - hdbscan
    - napari-plugin-engine >=0.1.4
    - napari-skimage-regionprops >=0.2.0
    - napari-tools-menu
    - numpy
    - pandas
    - python >=3.6
    - scikit-learn
    - umap-learn
    - qtpy
    - dask-core
    - napari
    - finesse
    - pytest
    - magicgui
    - scikit-image

test:
  imports:
    - napari_clusters_plotter
  commands:
    - pip list
    # - pip check
  requires:
    - oclgrind
    - pip

about:
  home: https://github.com/BiAPoL/napari-clusters-plotter
  summary: A plugin to use with napari for clustering objects according to their properties
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
    - lazigu
