{% set name = "napari-clusters-plotter" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0f7e5fef8a3b9c631e5265d67dd196c440054bb130b53a8ddf3d4f0fd6487817

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - cython >=0.27,<3  # hdbscan 0.8.33 has requirement cython<3,>=0.27
    - dask-core
    - hdbscan
    # - joblib  # not imported
    - magicgui
    - matplotlib-base
    - napari
    - napari-plugin-engine >=0.1.4
    - napari-skimage-regionprops >=0.3.1
    - napari-tools-menu
    - numpy >=1.21,<=1.23.5
    - pandas
    - python >=3.7
    - qtpy
    - scikit-image
    - scikit-learn
    - scipy
    - superqt
    - umap-learn

test:
  imports:
    - napari_clusters_plotter
  commands:
    - pip list
    - pip check
  requires:
    - oclgrind
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-clusters-plotter
  summary: A plugin to use with napari for clustering objects according to their properties
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/BiAPoL/napari-clusters-plotter

extra:
  recipe-maintainers:
    - goanpeca
    - haesleinhuepf
    - jaimergp
    - lazigu
