{% set name = "napari-clusters-plotter" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-clusters-plotter-{{ version }}.tar.gz
  sha256: 3947e0c3e2335046526e6b92159c013e3e7b498eecd5b766cf1cbdd0239776df

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - cython >=0.27,<3  # Testing
    - pip
    - python >=3.7
  run:
    - dask-core
    - hdbscan
    # - joblib  # not imported
    - magicgui
    - matplotlib-base
    - napari
    - napari-plugin-engine >=0.1.4
    - napari-skimage-regionprops >=0.3.1
    - napari-tools-menu
    - numpy >=1.21,<=1.23.5
    - pandas
    - python >=3.7
    - qtpy
    - scikit-image
    - scikit-learn
    - scipy
    - superqt
    - umap-learn

test:
  imports:
    - napari_clusters_plotter
  commands:
    - pip list
    - pip check
  requires:
    - oclgrind
    - pip

about:
  home: https://pypi.org/project/napari-clusters-plotter
  summary: A plugin to use with napari for clustering objects according to their properties
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/BiAPoL/napari-clusters-plotter

extra:
  recipe-maintainers:
    - goanpeca
    - haesleinhuepf
    - jaimergp
    - lazigu
