{% set name = "napari-clusters-plotter" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-clusters-plotter-{{ version }}.tar.gz
  sha256: d26e3933b80b30004398fe73929c0258a110244b4a14dd348be006e1ae22343d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - hdbscan
    - napari-plugin-engine >=0.1.4
    - napari-skimage-regionprops >=0.2.0
    - napari-tools-menu
    - numpy >=1.21,<=1.23.5
    - pandas
    - python >=3.6
    - scikit-learn
    - umap-learn
    - qtpy
    - dask-core
    - napari
    - finesse
    - magicgui
    - scikit-image
    - superqt

test:
  imports:
    - napari_clusters_plotter
  commands:
    - pip list
    - pip check
  requires:
    - oclgrind
    - pip

about:
  home: https://github.com/BiAPoL/napari-clusters-plotter
  summary: A plugin to use with napari for clustering objects according to their properties
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
    - lazigu
